"""Same-origin front end for isolated, installed-source head deformation calls."""

TEMPLATE = r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>HS2 源实现前向位移</title><style>
:root{color-scheme:dark;font-family:system-ui,"Microsoft YaHei",sans-serif;background:#111822;color:#e8edf4}*{box-sizing:border-box}body{margin:0}main{max-width:1480px;padding:22px;margin:auto}h1{font-size:25px;margin:0 0 9px}h2{font-size:17px;margin:0 0 12px}p{line-height:1.6}.muted{font-size:13px;color:#a8b7c9;overflow-wrap:anywhere}.panel{padding:16px;background:#1b2634;border:1px solid #364659;border-radius:10px;margin:14px 0}.controls{display:flex;flex-wrap:wrap;gap:12px;align-items:end}label{display:flex;flex-direction:column;gap:6px;font-size:13px}input,select,button{border:1px solid #617386;border-radius:5px;padding:8px;background:#111822;color:inherit}button{background:#25495c;cursor:pointer}button:disabled{opacity:.5;cursor:default}input{width:150px}input[readonly]{color:#a8b7c9}#control{min-width:280px;max-width:450px}#surface{max-width:360px}.inline{flex-direction:row;align-items:center}.inline input{width:auto}.views{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.view{background:#111822;border:1px solid #364659;border-radius:7px;padding:10px}.view h2{font-size:14px}canvas{width:100%;height:360px;display:block}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.metric{padding:12px;background:#111822;border-radius:6px;overflow-wrap:anywhere}.metric b{display:block;font-size:18px;margin-bottom:6px}.error{color:#ffb4a2!important}.warning{background:#302820;border-color:#85684b;color:#ffe2b6}#status{min-height:23px;color:#6ad5df}.legend{display:flex;gap:12px;align-items:center;font-size:12px;flex-wrap:wrap}.gradient{width:140px;height:9px;background:linear-gradient(90deg,#356391,#42d8d6,#ffe177,#ff7865)}summary{cursor:pointer;font-weight:600}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:380px;overflow:auto;background:#111822;font-size:12px;padding:12px}#protocol{overflow-wrap:anywhere}button:focus,input:focus,select:focus{outline:2px solid #65cbdc;outline-offset:2px}@media(max-width:950px){main{padding:14px}.views{grid-template-columns:1fr}canvas{height:330px}#control,#surface{min-width:0;max-width:100%}}
</style></head><body><main>
<h1>HS2 头部参数 → 源实现前向位移</h1>
<p class="muted">捕获当前配置与姿态，在隔离副本上调用已安装游戏 / ABMX 方法，再由 Unity BakeMesh 计算曲面。不写入当前游戏人物。此页面需要通过本地前向服务打开。</p>
<section class="panel warning"><b>固定姿态与表情下的计算位移</b><p class="muted">显示捕获配置按声明更新顺序得到的曲面变化。新候选未单独实机验收；软件的收尾验收范围见项目报告。原图谱的失败记录继续保留。</p></section>
<section class="panel"><div class="controls"><button id="context-button">捕获当前上下文</button><span id="context-label" class="muted">尚未捕获</span></div><p id="status" role="status" aria-live="polite">先捕获当前人物，再指定候选值。</p></section>
<section class="panel"><div class="controls">
<label>控制类别<select id="kind" disabled><option value="native">原生 59 参数</option><option value="abmx">ABMX 骨骼通道</option></select></label>
<label>参数<select id="control" disabled></select></label>
<label>当前值（冻结上下文）<input id="current" type="number" readonly></label>
<label>候选值<input id="candidate" type="number" step="any" disabled></label>
<label>原生范围<select id="range" disabled><option value="native">原生范围</option><option value="installed">已安装 SliderUnlocker 范围</option></select></label>
<label>ABMX Apply 次数<input id="apply-count" type="number" min="1" max="32" step="1" value="1" disabled></label>
<button id="evaluate-button" disabled>计算隔离副本</button></div><p class="muted" id="control-note">其余参数使用捕获配置；当前值来自冻结上下文。</p></section>
<section class="panel"><h2>目标最大位移 · 有界候选求解</h2><div class="controls">
<label>求解表面<select id="guide-surface" disabled></select></label>
<label>目标最大位移（游戏单位）<input id="target-max" type="number" min="0" step="any" placeholder="正有限数" disabled></label>
<label>候选方向（相对冻结当前值）<select id="direction" disabled><option value="1">增大</option><option value="-1">减小</option></select></label>
<label>搜索远端界限<input id="bound" type="number" step="any" placeholder="显式输入界限" disabled></label>
<button id="guide-button" disabled>按源实现有界求解</button></div>
<p class="muted">搜索起点是冻结当前值，远端界限由你指定。逐次调用源方法求解；端点未包围目标时会明确显示。只报告这个有限区间与迭代结果，不保证全域单调或最优。</p>
<div id="guidance-result" hidden><p id="guidance-status"></p><details><summary>求解记录</summary><pre id="guidance-record"></pre></details></div></section>
<div id="result" hidden>
<section class="panel"><div class="controls"><label>计算表面<select id="surface"></select></label><label class="inline"><input id="vectors" type="checkbox" checked>位移箭头</label><label>箭头显示倍数<input id="vector-gain" type="number" min="1" max="100" value="10"></label></div><p id="result-label"></p><div id="metrics" class="metrics"></div><p id="threshold" class="muted"></p><div class="legend"><span>灰点：reference</span><span>彩点：candidate</span><div class="gradient"></div><span id="color-max"></span></div></section>
<section class="views"><div class="view"><h2>XY · X 水平 / Y 垂直</h2><canvas id="xy"></canvas></div><div class="view"><h2>ZY · Z 水平 / Y 垂直</h2><canvas id="zy"></canvas></div><div class="view"><h2>XZ · X 水平 / Z 垂直</h2><canvas id="xz"></canvas></div></section>
<section class="panel"><h2>执行协议与输入配置</h2><p id="protocol"></p><p class="muted">完整姿态 / 参数与版本绑定见下方记录。位移使用返回坐标系的游戏几何单位，不能解释为毫米。三个视图投影全部顶点，会透视背侧点；影响区域由彩点和箭头定位，未附加未经验证的解剖标签。</p><details><summary>本次计算记录</summary><pre id="record"></pre></details></section>
</div></main><script>
"use strict";
const $=id=>document.getElementById(id),finite=value=>typeof value==="number"&&Number.isFinite(value);
let context=null,evaluation=null,entries=[],generation=0,busy=false;
const fmt=value=>finite(value)?(Math.abs(value)>=.01&&Math.abs(value)<1000?value.toPrecision(6):value.toExponential(5)):"未记录";
const vector=value=>"["+value.map(fmt).join(", ")+"]";
function status(message,error=false){$("status").textContent=message;$("status").classList.toggle("error",error);}
function option(select,value,label){const item=document.createElement("option");item.value=value;item.textContent=label;select.appendChild(item);}
function clearResult(){evaluation=null;$("result").hidden=true;$("surface").replaceChildren();$("guidance-result").hidden=true;}
function setBusy(value){busy=value;$("context-button").disabled=value;for(const id of ["kind","control","candidate","range","apply-count","evaluate-button","guide-surface","target-max","direction","bound","guide-button"])$(id).disabled=value||!context;$("range").disabled=value||!context||$("kind").value!=="native";}
async function post(url,body){const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});let data;try{data=await response.json();}catch{throw Error("服务未返回 JSON（HTTP "+response.status+"）");}if(!response.ok||data?.ok===false){const error=data?.error;throw Error(typeof error==="string"?error:(error?.message||data?.message||"HTTP "+response.status));}return data;}
function controlsOf(value){return Array.isArray(value)?value:(value?.shapes||[]);}
function validateContext(value){
 if(!value||typeof value.context_id!=="string"||!value.context_id||!Array.isArray(value.identity?.native59)||value.identity.native59.length!==59||!value.identity.native59.every(finite))throw Error("上下文缺少完整的 59 个原生值");
 const controls=controlsOf(value.native_controls);if(controls.length!==59||new Set(controls.map(c=>c.index)).size!==59||controls.some(c=>!Number.isInteger(c.index)||c.index<0||c.index>=59||typeof c.name!=="string"))throw Error("上下文缺少完整参数名称 / 编号");
 if(!Array.isArray(value.selected_abmx_bones)||value.selected_abmx_bones.length>3||value.selected_abmx_bones.some(b=>typeof(b?.name||b)!=="string"))throw Error("ABMX 可选骨骼声明无效");
 if(!Array.isArray(value.surfaces)||!value.surfaces.length||value.surfaces.some(s=>typeof s.renderer_path!=="string"||typeof s.mesh_name!=="string"||!Number.isInteger(s.vertex_count)||s.vertex_count<1))throw Error("上下文表面声明无效");
}
function modifier(name){const declared=context.selected_abmx_bones.find(b=>(b?.name||b)===name),rows=context.identity.abmx_runtime?.bones||[];const found=rows.find(b=>b.name===name)||(typeof declared==="object"?declared:null);return {name,scale:found?.scale||[1,1,1],position:found?.position||[0,0,0],rotation:found?.rotation||[0,0,0],length:found?.length??1};}
function refreshControls(){
 generation++;clearResult();entries=[];$("control").replaceChildren();
 if(!context)return;
 if($("kind").value==="native")for(const control of controlsOf(context.native_controls)){const entry={id:"native_"+control.index,kind:"native",index:control.index,label:String(control.index).padStart(2,"0")+" · "+control.name};entries.push(entry);option($("control"),entry.id,entry.label);}
 else for(const row of context.selected_abmx_bones){const name=row?.name||row;for(const channel of ["scale","position","rotation","length"]){for(const axis of channel==="length"?[null]:[0,1,2]){const entry={id:name+"_"+channel+(axis??""),kind:"abmx",name,channel,axis,label:name+" · "+channel+(axis===null?"":" "+"XYZ"[axis])};entries.push(entry);option($("control"),entry.id,entry.label);}}}
 if($("kind").value==="native"&&entries.some(e=>e.index===30))$("control").value="native_30";
 setBusy(false);if(!entries.length){$("evaluate-button").disabled=true;$("guide-button").disabled=true;$("candidate").disabled=true;status("此上下文没有可选的 ABMX 骨骼。");return;}changeControl();
}
function changeControl(){generation++;clearResult();const entry=entries.find(e=>e.id===$("control").value);if(!entry)return;const value=entry.kind==="native"?context.identity.native59[entry.index]:(entry.channel==="length"?modifier(entry.name).length:modifier(entry.name)[entry.channel][entry.axis]);if(!finite(value)){status("当前骨骼通道值无效；请重新捕获上下文。",true);$("evaluate-button").disabled=true;$("guide-button").disabled=true;return;}$("current").value=String(value);$("candidate").value=String(value);$("bound").value="";$("control-note").textContent=entry.kind==="native"?"仅替换这个原生系数；提交完整 59 值，其他系数保持冻结配置。":"仅替换这个 ABMX 通道；其他轴使用冻结的 modifier 值。位置使用骨骼局部游戏单位，旋转使用度，scale / length 使用插件倍率。";status("候选尚未计算。当前值来自上下文 "+context.context_id+"。");setBusy(false);}
async function createContext(){if(busy)return;const token=++generation;context=null;clearResult();$("control").replaceChildren();$("guide-surface").replaceChildren();$("current").value="";$("candidate").value="";$("context-label").textContent="正在捕获";setBusy(true);status("正在捕获当前配置、姿态与源方法状态…");try{const value=await post("/api/context",{});if(token!==generation)return;validateContext(value);context=value;value.surfaces.forEach(surface=>option($("guide-surface"),surface.renderer_path,surface.mesh_name+" · "+surface.vertex_count+" vertices"));const head=value.surfaces.find(surface=>surface.mesh_name==="o_head");if(head)$("guide-surface").value=head.renderer_path;$("context-label").textContent="context "+value.context_id+" · head "+value.identity.head_id+" · "+value.surfaces.length+" 个表面";refreshControls();}catch(error){if(token===generation){context=null;status("上下文失败："+error.message,true);$("context-label").textContent="上下文不可用";}}finally{setBusy(false);}}
function requestBody(){
 if(!context)throw Error("先捕获上下文");const entry=entries.find(e=>e.id===$("control").value),text=$("candidate").value,countText=$("apply-count").value;if(!entry||text.trim()===""||countText.trim()==="")throw Error("请输入候选值与 Apply 次数");const value=Number(text),count=Number(countText);if(!finite(value)||!Number.isInteger(count)||count<1||count>32)throw Error("候选值必须有限；Apply 次数为 1..32 整数");const body={context_id:context.context_id,apply_count:count,range_mode:entry.kind==="native"?$("range").value:"native"};
 if(entry.kind==="native"){body.native_values=context.identity.native59.slice();body.native_values[entry.index]=value;}
 else {const bone=modifier(entry.name),patch={name:entry.name};if(entry.channel==="length")patch.length=value;else{const values=bone[entry.channel].slice();if(values.length!==3||!values.every(finite))throw Error("冻结骨骼向量无效");values[entry.axis]=value;patch[entry.channel]=values;}body.bones=[patch];}
 return body;
}
function validateEvaluation(value){
 if(!value||value.context_id!==context.context_id||value.live_state_unchanged!==true||value.final_game_acceptance_verified!==false)throw Error("上下文 / 隔离检查 / 最终验收状态不符合协议");
 if(JSON.stringify(value.identity?.native59)!==JSON.stringify(context.identity.native59))throw Error("结果绑定的完整原生输入不同");
 if(!Array.isArray(value.surfaces)||!value.surfaces.length)throw Error("结果缺少曲面");
 const paths=new Set();for(const surface of value.surfaces){const declaration=context.surfaces.find(s=>s.renderer_path===surface.renderer_path);if(!declaration||paths.has(surface.renderer_path)||surface.mesh_name!==declaration.mesh_name)throw Error("结果曲面声明不匹配");paths.add(surface.renderer_path);for(const field of ["reference","candidate","delta"]){const points=surface[field];if(!Array.isArray(points)||points.length!==declaration.vertex_count||points.some(p=>!Array.isArray(p)||p.length!==3||!p.every(finite)))throw Error("曲面顶点数量 / 数值不匹配");}}if(paths.size!==context.surfaces.length)throw Error("结果曲面覆盖不完整");
}
function showEvaluation(value,request,guidance=null,preferredPath=null){
 validateEvaluation(value);evaluation=value;$("surface").replaceChildren();value.surfaces.forEach(surface=>option($("surface"),surface.renderer_path,surface.mesh_name+" · "+surface.reference.length+" vertices"));const head=value.surfaces.find(surface=>surface.mesh_name==="o_head"),preferred=value.surfaces.find(surface=>surface.renderer_path===preferredPath);if(preferred||head)$("surface").value=(preferred||head).renderer_path;$("guide-surface").value=$("surface").value;$("result").hidden=false;$("protocol").textContent=value.protocol;$("record").textContent=JSON.stringify({request,guidance,result_identity:value.identity,protocol:value.protocol,implementation:value.implementation,pose_policy:value.pose_policy,live_state_unchanged:value.live_state_unchanged,final_game_acceptance_verified:value.final_game_acceptance_verified},null,2);$("result-label").textContent="源实现计算 · Apply "+request.apply_count+" 次 · 当前游戏状态未被改写 · 此候选未单独实机验收";render();
}
async function evaluateCandidate(){if(busy)return;let request;try{request=requestBody();}catch(error){status(error.message,true);return;}const preferred=$("guide-surface").value,token=++generation;clearResult();setBusy(true);status("正在隔离副本上调用源实现…");try{const value=await post("/api/evaluate",request);if(token!==generation)return;showEvaluation(value,request,null,preferred);status("计算完成；已返回声明表面，此候选未单独实机验收。");}catch(error){if(token===generation){clearResult();status("计算失败："+error.message,true);}}finally{setBusy(false);}}
function guidanceRequest(){
 const request=requestBody(),entry=entries.find(value=>value.id===$("control").value),targetText=$("target-max").value,boundText=$("bound").value;if(!targetText.trim()||!boundText.trim())throw Error("请显式输入正目标位移与搜索界限");const target=Number(targetText),bound=Number(boundText),start=Number($("current").value),direction=Number($("direction").value);if(!finite(target)||target<=0||!finite(bound)||!finite(start)||![-1,1].includes(direction)||(bound-start)*direction<=0)throw Error("目标位移须为正有限数；界限必须位于已选方向的冻结当前值远端");const control=entry.kind==="native"?{kind:"native",index:entry.index}:{kind:"abmx",name:entry.name,channel:entry.channel};if(entry.kind==="abmx"&&entry.channel!=="length")control.axis=entry.axis;const path=$("guide-surface").value||context.surfaces.find(surface=>surface.mesh_name==="o_head")?.renderer_path;if(!context.surfaces.some(surface=>surface.renderer_path===path))throw Error("请选择上下文中的求解表面");return {request,control,surface_path:path,target_max:target,bound};
}
function validateGuidance(value){const g=value?.guidance;if(!g||!["target_bracketed","target_not_bracketed","residual_limit"].includes(g.status)||![g.candidate_value,g.max_displacement,g.target_max,g.absolute_residual].every(finite)||g.target_max<=0||g.max_displacement<0||g.absolute_residual<0||!Number.isInteger(g.iterations)||g.iterations<0||typeof g.note!=="string")throw Error("有界求解结果格式无效");return g;}
async function guideCandidate(){
 if(busy)return;let body;try{body=guidanceRequest();}catch(error){status(error.message,true);return;}const token=++generation;clearResult();setBusy(true);status("正在指定区间内调用源方法求解…");try{const value=await post("/api/guide",body);if(token!==generation)return;const g=validateGuidance(value),actualRequest=JSON.parse(JSON.stringify(body.request));if(body.control.kind==="native")actualRequest.native_values[body.control.index]=g.candidate_value;else{const patch=actualRequest.bones.find(bone=>bone.name===body.control.name);if(body.control.channel==="length")patch.length=g.candidate_value;else patch[body.control.channel][body.control.axis]=g.candidate_value;}showEvaluation(value.evaluation,actualRequest,g,body.surface_path);$("candidate").value=String(g.candidate_value);const messages={target_bracketed:"已返回包围目标区间中的有限迭代候选。",target_not_bracketed:"搜索端点未包围目标；本次未证明达到目标。",residual_limit:"有限迭代仍有残余误差；本次未证明达到目标。"};$("guidance-status").textContent=messages[g.status]+" 候选值 "+fmt(g.candidate_value)+"；计算最大位移 "+fmt(g.max_displacement)+"；目标 "+fmt(g.target_max)+"；绝对残差 "+fmt(g.absolute_residual)+"；迭代 "+g.iterations+" 次。"+" 只适用于当前配置和声明区间；新候选未单独实机验收。";$("guidance-status").classList.toggle("error",g.status!=="target_bracketed");$("guidance-record").textContent=JSON.stringify({search_request:body,guidance:g},null,2);$("guidance-result").hidden=false;status(g.status==="target_bracketed"?"有界源方法求解已返回候选；此候选未单独实机验收。":"有界求解已返回明确限制；请查看残差与端点状态。",g.status!=="target_bracketed");}catch(error){if(token===generation){clearResult();status("有界求解失败："+error.message,true);}}finally{setBusy(false);}
}
function summarize(surface){const minimum=[Infinity,Infinity,Infinity],maximum=[-Infinity,-Infinity,-Infinity],plotMin=[Infinity,Infinity,Infinity],plotMax=[-Infinity,-Infinity,-Infinity],mean=[0,0,0];let max=0,sumSquares=0;for(let i=0;i<surface.reference.length;i++){const reference=surface.reference[i],candidate=surface.candidate[i],delta=surface.delta[i],distance=Math.hypot(...delta);max=Math.max(max,distance);sumSquares+=distance*distance;for(let axis=0;axis<3;axis++){minimum[axis]=Math.min(minimum[axis],reference[axis]);maximum[axis]=Math.max(maximum[axis],reference[axis]);plotMin[axis]=Math.min(plotMin[axis],reference[axis],candidate[axis]);plotMax[axis]=Math.max(plotMax[axis],reference[axis],candidate[axis]);mean[axis]+=delta[axis]/surface.reference.length;}}const diagonal=Math.hypot(...minimum.map((value,i)=>maximum[i]-value)),threshold=diagonal*1e-6;return {max,rms:Math.sqrt(sumSquares/surface.reference.length),mean,diagonal,threshold,affected:surface.delta.filter(d=>Math.hypot(...d)>threshold).length,plotMin,plotMax};}
function metric(value,label){const item=document.createElement("div");item.className="metric";const strong=document.createElement("b");strong.textContent=value;const text=document.createElement("span");text.className="muted";text.textContent=label;item.append(strong,text);$("metrics").appendChild(item);}
function color(value){const t=Math.min(1,Math.max(0,value)),stops=[[53,99,145],[66,216,214],[255,225,119],[255,120,101]],x=t*3,index=Math.min(2,Math.floor(x)),weight=x-index;return "rgb("+stops[index].map((v,i)=>Math.round(v*(1-weight)+stops[index+1][i]*weight)).join(",")+")";}
function draw(id,axes,surface,stats){const canvas=$(id),rect=canvas.getBoundingClientRect(),ratio=window.devicePixelRatio||1,width=rect.width,height=rect.height;canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);const painter=canvas.getContext("2d");painter.scale(ratio,ratio);const [a,b]=axes,padding=26,scale=Math.min((width-2*padding)/Math.max(stats.plotMax[a]-stats.plotMin[a],1e-10),(height-2*padding)/Math.max(stats.plotMax[b]-stats.plotMin[b],1e-10)),project=v=>[width/2+(v[a]-(stats.plotMax[a]+stats.plotMin[a])/2)*scale,height/2-(v[b]-(stats.plotMax[b]+stats.plotMin[b])/2)*scale];painter.fillStyle="#8296ac55";surface.reference.forEach(v=>{const p=project(v);painter.fillRect(p[0],p[1],1.2,1.2);});const gain=Math.min(100,Math.max(1,Number($("vector-gain").value)||1));if($("vectors").checked){painter.strokeStyle="#69d9df80";painter.lineWidth=.7;painter.beginPath();surface.reference.forEach((v,i)=>{if(Math.hypot(...surface.delta[i])<=stats.threshold)return;const start=project(v),end=project(v.map((value,j)=>value+surface.delta[i][j]*gain)),dx=end[0]-start[0],dy=end[1]-start[1],length=Math.hypot(dx,dy);painter.moveTo(...start);painter.lineTo(...end);if(length>3){const ux=dx/length,uy=dy/length;painter.moveTo(end[0]-ux*3-uy*1.5,end[1]-uy*3+ux*1.5);painter.lineTo(...end);painter.lineTo(end[0]-ux*3+uy*1.5,end[1]-uy*3-ux*1.5);}});painter.stroke();}surface.candidate.forEach((v,i)=>{const p=project(v),d=Math.hypot(...surface.delta[i]);painter.fillStyle=color(stats.max?d/stats.max:0);painter.fillRect(p[0],p[1],1.5,1.5);});painter.fillStyle="#a8b7c9";painter.font="11px system-ui";painter.fillText("候选点位置不放大；箭头显示倍数 "+gain,9,height-7);}
function render(){if(!evaluation)return;const surface=evaluation.surfaces.find(s=>s.renderer_path===$("surface").value);if(!surface)return;const stats=summarize(surface);$("metrics").replaceChildren();metric(fmt(stats.max),"最大位移 · 返回坐标系的游戏几何单位");metric(stats.diagonal>0?fmt(stats.max/stats.diagonal*100)+" %":"参考包围盒退化","最大位移 / 该表面 reference 对角线");metric(fmt(stats.rms),"RMS 位移 · 游戏几何单位");metric(vector(stats.mean),"平均位移方向 [X,Y,Z]");metric(stats.affected+" / "+surface.reference.length,"超过显示阈值的顶点数");metric(fmt(stats.diagonal),"reference 包围盒对角线 · 单位基准");$("threshold").textContent="影响区的显示阈值为 "+fmt(stats.threshold)+"（reference 对角线 × 1e-6），仅用于绘图标记，不是验收门槛。表面路径："+surface.renderer_path;$("color-max").textContent="颜色范围 0 → "+fmt(stats.max);draw("xy",[0,1],surface,stats);draw("zy",[2,1],surface,stats);draw("xz",[0,2],surface,stats);}
$("context-button").addEventListener("click",createContext);$("evaluate-button").addEventListener("click",evaluateCandidate);$("guide-button").addEventListener("click",guideCandidate);$("kind").addEventListener("change",refreshControls);$("control").addEventListener("change",changeControl);for(const id of ["candidate","range","apply-count","target-max","direction","bound","guide-surface"]){$(id).addEventListener("input",()=>{if(!busy){generation++;clearResult();status("候选输入已改变；请重新计算。");}});}$("surface").addEventListener("change",()=>{$("guide-surface").value=$("surface").value;$("guidance-result").hidden=true;render();});$("vectors").addEventListener("change",render);$("vector-gain").addEventListener("input",render);window.addEventListener("resize",render);
</script></body></html>'''
